### ISSUE TITLE
screen goes grey after clicking "clip"

### ISSUE THREAD

**Issue by nift-d** [Alex0Blackwell/copy-paste-anything#3]
as in title. the text is copied properly, but its impossible to select passages correctly, because of the screen going grey while selecting. after selection is done the screen goes back to normal.

manjaro linux, kde

**Comment by Alex0Blackwell** [comment]
Thanks for creating an issue for this @nift-d, I will start investigating now.

**Comment by Alex0Blackwell** [comment]
@nift-d the reason the screen is going grey while selecting is your screen compositor or window manager doesn't support transparency. When the program captures a section of the screen, it actually makes the window size that of the screen, and sets itself to be mostly transparent. On Manjaro KDE you need a compositor that supports transparency.

Check to see if your composition manager supports transparency. If it does, turn it on :)
If it doesn't, you can install a composition manager that does support transparency. I've been using Compton on Manjaro XFCE for years and I think it works great!

Let me know how that goes, and feel free to continue this thread for some more help.

**Comment by nift-d** [comment]
thx for investigation. I had no idea how to check whether the compositor does support transparency, so I just changed from OpenGL 2.0 to 3.1. And I guess it is save to say that it does support transparency using OpenGL 3.1.

while we are at it:
I don't see what the button is good for. it would be nice if just worked after I used the shortcut.

**Comment by Alex0Blackwell** [comment]
Hmm, good idea @nift-d! I made a few changes yesterday so it uses a `Makefile` now. I will add that as a command, maybe
`Make run-simple`. How does that sound? I can tag you in a PR for this change.

**Comment by nift-d** [comment]
sounds great, you could even think about an option that pasts the copied content on to TTS for reading it out.

since you seem to be the nicest person on the interwebs, maybe you can help me with the start script:
I tried to start you program using a script with:
`#! /usr/bin/zsh

/home/dh/git/copy-paste-anything make run`
its in .local/bin/copypasteanything.zsh and the keyboard shortcut directs to it.

it does work when I start it from shell, but it does not, when I use the keyboard shortcut. Any suggestions?

**Comment by Alex0Blackwell** [comment]
I'm on XFCE so maybe it's different, but I went with something like this:
![image](https://user-images.githubusercontent.com/31634087/140250814-b327599c-b62e-495e-8a34-4757c85f32cf.png)

The command is
```
make -C ~/your/path/to/copy-paste-anything/ run
```

and when I add `run-simple` it will be 
```
make -C ~/your/path/to/copy-paste-anything/ run-simple
```

I think this is the simplest way to get this running, let me know if you have any luck @nift-d!

**Comment by nift-d** [comment]
thx for the advice, but it did not work by using the keyboard shortcut. it does work when I test it in the terminal though.

I use shortcuts for nerd dictation in the same manner and it does work. I am confused here. shortcuts are crucial for usability - no shortcut, no usage..

**Comment by Alex0Blackwell** [comment]
I added support for `run-simple`. With your `.zsh` script try
```
#! /usr/bin/zsh

~/dh/git/copy-paste-anything make run-simple
```

**Comment by nift-d** [comment]
sorry, forgot about that..
```
#! /usr/bin/zsh  
make -C ~/git/copy-paste-anything run-simple
```
did work..
